### ISSUE TITLE
image_size module and imagesize_py model

### ISSUE THREAD

**Issue by oneTaken** [scardine/image_size#12]
I found the question [Get Image size WITHOUT loading image into memory](https://stackoverflow.com/questions/15800704/get-image-size-without-loading-image-into-memory),
 and I go to the links to this repository and another implementation [imagesize_py](https://github.com/shibukawa/imagesize_py)。

which repo should I use?
I'm a little confused how to use your code.

**Comment by pauloscardine** [comment]
If you are only using JPEG/JPEG 2000/PNG/GIF/TIFF go with [imagesize_py](https://github.com/shibukawa/imagesize_py), the one at [my repo](https://github.com/scardine/image_size) knows about a couple other image types. My answer is from 2013 and this is just throwaway code to illustrate that answer - over the time a few people sent patches but it is what it is.
