### ISSUE TITLE
fails for some files (e.g. png) on Windows

### ISSUE THREAD

**Issue by gityhup** [scardine/image_size#3]
PNG files, for example, will have "data" truncated to "89:50:4e:47:0a", causing them to be misdetected as an (invalid) ICO file.

Changing 
```
with open(file_path) as input:
```
to 
```
with open(file_path, 'rb') as input:
```
solves this on this OS that does not treat binary and text files differently.

**Comment by scardine** [comment]
Thanks, fixed.
